# Generated by Django 5.2.17 on 2026-08-25 15:20

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('media_assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('key', models.CharField(max_length=60)),
                ('label', models.CharField(max_length=80)),
                ('field_type', models.CharField(choices=[('short_text', 'Texto corto'), ('decimal', 'Número decimal'), ('date', 'Fecha'), ('boolean', 'Booleano'), ('single_select', 'Selección única')], max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('help_text', models.CharField(blank=True, max_length=160)),
                ('is_required', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_filterable', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='inventory.inventory')),
            ],
            options={
                'ordering': ('position', 'created_at'),
                'indexes': [models.Index(fields=['inventory', 'is_active', 'position'], name='custom_field_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('inventory', 'key'), name='custom_field_unique_key_per_inventory'), models.UniqueConstraint(models.F('inventory'), django.db.models.functions.text.Lower('label'), name='custom_field_unique_label_per_inventory')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('catalog_status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('archived', 'Archivado')], default='active', max_length=12)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('currency', models.CharField(default='CLP', editable=False, max_length=3)),
                ('extra_attributes', models.JSONField(blank=True, default=dict)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.inventory')),
                ('primary_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_products', to='media_assets.mediaasset')),
            ],
            options={
                'ordering': ('name', 'created_at'),
                'indexes': [models.Index(fields=['inventory', 'catalog_status', 'name'], name='product_catalog_idx')],
                'constraints': [models.UniqueConstraint(models.F('inventory'), django.db.models.functions.text.Lower('name'), condition=models.Q(('catalog_status', 'archived'), _negated=True), name='product_unique_active_name_per_inventory'), models.CheckConstraint(condition=models.Q(('purchase_price__isnull', True), ('purchase_price__gte', 0), _connector='OR'), name='product_purchase_price_not_negative'), models.CheckConstraint(condition=models.Q(('sale_price__isnull', True), ('sale_price__gte', 0), _connector='OR'), name='product_sale_price_not_negative'), models.CheckConstraint(condition=models.Q(('currency', 'CLP')), name='product_currency_is_clp'), models.CheckConstraint(condition=models.Q(models.Q(('archived_at__isnull', False), ('catalog_status', 'archived')), models.Q(('catalog_status', 'archived'), _negated=True), _connector='OR'), name='product_archived_requires_timestamp')],
            },
        ),
    ]
