# Generated by Django 5.2.17 on 2026-08-25 15:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_customfielddefinition_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='balance', serialize=False, to='inventory.product')),
                ('on_hand', models.IntegerField(default=0)),
                ('reserved', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='inventory.inventory')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('on_hand__gte', 0)), name='stock_balance_on_hand_not_negative'), models.CheckConstraint(condition=models.Q(('reserved__gte', 0)), name='stock_balance_reserved_not_negative'), models.CheckConstraint(condition=models.Q(('reserved__lte', models.F('on_hand'))), name='stock_balance_available_not_negative')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('movement_type', models.CharField(choices=[('entry', 'Entrada'), ('exit', 'Salida'), ('shrinkage', 'Merma'), ('correction', 'Corrección')], max_length=12)),
                ('quantity', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=280)),
                ('reference_type', models.CharField(blank=True, max_length=40)),
                ('reference_public_id', models.CharField(blank=True, max_length=80)),
                ('correlation_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('corrects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='inventory.stockmovement')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.inventory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.product')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['product', '-created_at'], name='stock_movement_product_idx'), models.Index(fields=['inventory', '-created_at'], name='stock_movement_ledger_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='stock_movement_quantity_not_zero'), models.CheckConstraint(condition=models.Q(('balance_after__gte', 0)), name='stock_movement_balance_not_negative'), models.CheckConstraint(condition=models.Q(models.Q(('movement_type', 'entry'), ('quantity__gt', 0)), models.Q(('movement_type__in', ('exit', 'shrinkage')), ('quantity__lt', 0)), ('movement_type', 'correction'), _connector='OR'), name='stock_movement_sign_matches_type')],
            },
        ),
    ]
