# Generated by Django 5.2.17 on 2026-08-25 18:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockbalance_stockmovement'),
        ('media_assets', '0002_alter_mediaasset_purpose'),
        ('organisations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InventoryAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('alert_type', models.CharField(choices=[('low_stock', 'Stock bajo'), ('out_of_stock', 'Sin stock')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('resolved', 'Resuelta')], default='active', max_length=12)),
                ('threshold', models.PositiveIntegerField()),
                ('available_quantity', models.PositiveIntegerField()),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='inventory.inventory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_alerts', to='inventory.product')),
            ],
            options={
                'ordering': ('-opened_at', '-id'),
                'indexes': [models.Index(fields=['inventory', 'status', '-opened_at'], name='inventory_alert_feed_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('product', 'alert_type'), name='inventory_alert_one_active_type')],
            },
        ),
        migrations.CreateModel(
            name='InventoryExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'XLSX')], max_length=8)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'En cola'), ('processing', 'Procesando'), ('succeeded', 'Completada'), ('failed', 'Fallida')], default='queued', max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_exports', to=settings.AUTH_USER_MODEL)),
                ('file_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_exports', to='media_assets.mediaasset')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exports', to='inventory.inventory')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_exports', to='organisations.organisation')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['inventory', 'status', '-created_at'], name='inventory_export_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('analysing', 'Analizando'), ('awaiting_mapping', 'Esperando mapeo'), ('queued', 'En cola'), ('processing', 'Procesando'), ('succeeded', 'Completada'), ('completed_with_errors', 'Completada con errores'), ('failed', 'Fallida')], default='analysing', max_length=24)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('headers', models.JSONField(blank=True, default=list)),
                ('preview_rows', models.JSONField(blank=True, default=list)),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('row_errors', models.JSONField(blank=True, default=list)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_imports', to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imports', to='inventory.inventory')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_imports', to='organisations.organisation')),
                ('report_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_import_reports', to='media_assets.mediaasset')),
                ('source_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_import_sources', to='media_assets.mediaasset')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['inventory', 'status', '-created_at'], name='inventory_import_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('inventory', 'source_asset'), name='inventory_import_unique_source')],
            },
        ),
        migrations.CreateModel(
            name='ProductMediaAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='product_attachment', to='media_assets.mediaasset')),
                ('attached_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_attachments', to='inventory.product')),
            ],
            options={
                'ordering': ('position', 'created_at'),
                'indexes': [models.Index(fields=['product', 'position'], name='product_media_position_idx')],
            },
        ),
    ]
