# Generated by Django 5.2.17 on 2026-09-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_notificationdelivery_outboxevent_and_more'),
        ('organisations', '0004_organisation_bank_details'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notifications_tenant_user_idx',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('email', 'Email')], max_length=16),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organisation', 'created_at'], name='notifications_tenant_idx'),
        ),
    ]
