# Generated by Django 5.2.17 on 2026-08-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="photo_asset_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
