# Generated by Django 5.2.17 on 2026-08-25 09:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('purpose', models.CharField(choices=[('product_image', 'Product image'), ('payment_receipt', 'Payment receipt'), ('shipping_evidence', 'Shipping evidence'), ('import_file', 'Import file')], max_length=32)),
                ('object_key', models.CharField(editable=False, max_length=500, unique=True)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=120)),
                ('expected_size', models.PositiveBigIntegerField()),
                ('actual_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending upload'), ('uploaded', 'Uploaded'), ('ready', 'Ready'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_media_assets', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='organisations.organisation')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organisation', 'purpose', 'status'], name='media_asset_tenant_status_idx')],
            },
        ),
    ]
