# Generated by Django 5.2.17 on 2026-08-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='purpose',
            field=models.CharField(choices=[('product_image', 'Product image'), ('payment_receipt', 'Payment receipt'), ('shipping_evidence', 'Shipping evidence'), ('import_file', 'Import file'), ('import_report', 'Import report'), ('inventory_export', 'Inventory export')], max_length=32),
        ),
    ]
