# Generated by Django 5.2.17 on 2026-08-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_assets", "0003_shipping_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaasset",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("product_image", "Product image"),
                    ("profile_photo", "Profile photo"),
                    ("organisation_logo", "Organisation logo"),
                    ("payment_receipt", "Payment receipt"),
                    ("shipping_evidence", "Shipping evidence"),
                    ("import_file", "Import file"),
                    ("import_report", "Import report"),
                    ("inventory_export", "Inventory export"),
                    ("shipping_label", "Shipping label"),
                ],
                max_length=32,
            ),
        ),
    ]
