# Generated by Django 5.2.17 on 2026-08-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_assets', '0004_profile_and_logo_purposes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='variants',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
