# Generated by Django 5.2.17 on 2026-08-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="organisation",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="logo_asset_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
