# Generated by Django 5.2.17 on 2026-09-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0003_organisation_profile_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="organisation",
            name="bank_account_type",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="organisation",
            name="bank_confirmation_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="organisation",
            name="bank_holder_tax_id",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="organisation",
            name="bank_name",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
