# Generated by Django 5.2.17 on 2026-08-25 07:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('scope', models.CharField(max_length=80)),
                ('key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('succeeded', 'Succeeded')], default='processing', max_length=16)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('response_status', models.PositiveSmallIntegerField(default=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to='organisations.organisation')),
            ],
            options={
                'indexes': [models.Index(fields=['organisation', 'scope', 'created_at'], name='audit_idempotency_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('organisation', 'scope', 'key'), name='audit_idempotency_tenant_scope_key_unique')],
            },
        ),
    ]
