# Generated by Django 5.2.17 on 2026-08-25 07:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('organisations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(max_length=120)),
                ('object_type', models.CharField(blank=True, max_length=80)),
                ('object_public_id', models.CharField(blank=True, max_length=80)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('denied', 'Denied'), ('failure', 'Failure')], default='success', max_length=16)),
                ('correlation_id', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='organisations.organisation')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organisation', 'action', 'created_at'], name='audit_event_tenant_action_idx'), models.Index(fields=['correlation_id'], name='audit_event_correlation_idx')],
            },
        ),
    ]
