# Generated by Django 5.2.17 on 2026-08-25 07:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('key', models.CharField(max_length=120)),
                ('enabled', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_flags', to='organisations.organisation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('key',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('organisation__isnull', True)), fields=('key',), name='configuration_global_flag_unique'), models.UniqueConstraint(condition=models.Q(('organisation__isnull', False)), fields=('organisation', 'key'), name='configuration_tenant_flag_unique')],
            },
        ),
        migrations.CreateModel(
            name='OperationalParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('key', models.CharField(max_length=120)),
                ('value', models.JSONField()),
                ('description', models.CharField(blank=True, max_length=240)),
                ('sensitive', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operational_parameters', to='organisations.organisation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('key',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('organisation__isnull', True)), fields=('key',), name='configuration_global_parameter_unique'), models.UniqueConstraint(condition=models.Q(('organisation__isnull', False)), fields=('organisation', 'key'), name='configuration_tenant_parameter_unique')],
            },
        ),
    ]
