# Generated by Django 5.2.17 on 2026-08-25 09:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
        ('organisations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider', models.CharField(max_length=80)),
                ('ciphertext', models.TextField(editable=False)),
                ('key_version', models.PositiveSmallIntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encrypted_credentials', to='organisations.organisation')),
            ],
            options={
                'ordering': ('provider', '-created_at'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('organisation', 'provider'), name='configuration_active_credential_unique')],
            },
        ),
    ]
