# Generated by Django 5.2.17 on 2026-08-26 08:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0006_backfill_stock_alerts'),
        ('organisations', '0002_initial'),
        ('sales', '0003_order_paymentwebhookevent_attempts_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('number', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('preparing', 'En preparación'), ('dispatched', 'Despachado'), ('delivery_check', 'Chequeo de entrega'), ('delivered', 'Entregado'), ('issue', 'Incidencia'), ('returned', 'Devuelto'), ('cancelled', 'Cancelado'), ('closed', 'Cerrado')], default='pending', max_length=24)),
                ('delivery_mode', models.CharField(max_length=16)),
                ('recipient_name', models.CharField(blank=True, max_length=160)),
                ('address_line', models.CharField(blank=True, max_length=240)),
                ('municipality', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('delivery_notes', models.CharField(blank=True, max_length=500)),
                ('carrier', models.CharField(blank=True, max_length=120)),
                ('tracking_code', models.CharField(blank=True, max_length=120)),
                ('tracking_url', models.URLField(blank=True)),
                ('public_token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('public_token_ciphertext', models.TextField(editable=False)),
                ('public_token_expires_at', models.DateTimeField()),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='inventory.inventory')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shipment', to='sales.order')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='organisations.organisation')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='FollowUpSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('delivery_check', 'Chequeo de entrega'), ('reminder', 'Recordatorio'), ('autoclose', 'Autocierre')], max_length=32)),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('due', 'Vencido'), ('sent', 'Enviado'), ('cancelled', 'Cancelado')], default='scheduled', max_length=16)),
                ('due_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_follow_ups', to='organisations.organisation')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follow_ups', to='shipping.shipment')),
            ],
            options={
                'ordering': ('due_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DeliveryConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('outcome', models.CharField(choices=[('received', 'Sí, lo recibí'), ('needs_help', 'No, necesito ayuda')], max_length=24)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_confirmation', to='shipping.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(max_length=80)),
                ('from_status', models.CharField(blank=True, max_length=24)),
                ('to_status', models.CharField(blank=True, max_length=24)),
                ('title', models.CharField(max_length=180)),
                ('detail', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timeline', to='shipping.shipment')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['organisation', 'status', '-created_at'], name='shipping_shipment_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.UniqueConstraint(fields=('organisation', 'number'), name='shipping_shipment_tenant_number_unique'),
        ),
        migrations.AddIndex(
            model_name='followupschedule',
            index=models.Index(fields=['status', 'due_at'], name='shipping_followup_due_idx'),
        ),
    ]
