# Generated by Django 5.2.17 on 2026-09-23 19:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0006_backfill_stock_alerts'),
        ('media_assets', '0006_alter_mediaasset_purpose'),
        ('organisations', '0004_organisation_bank_details'),
        ('sales', '0005_buyer_region_commune'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('number', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('dispatched', 'Despachado'), ('delivered', 'Entregado')], default='pending', max_length=24)),
                ('delivery_mode', models.CharField(max_length=16)),
                ('recipient_name', models.CharField(blank=True, max_length=160)),
                ('recipient_tax_id', models.CharField(blank=True, max_length=16)),
                ('address_line', models.CharField(blank=True, max_length=240)),
                ('commune', models.CharField(blank=True, max_length=120)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('delivery_notes', models.CharField(blank=True, max_length=500)),
                ('carrier', models.CharField(blank=True, max_length=120)),
                ('tracking_code', models.CharField(blank=True, max_length=120)),
                ('tracking_url', models.URLField(blank=True)),
                ('dispatch_note', models.CharField(blank=True, max_length=500)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='inventory.inventory')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shipment', to='sales.order')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='organisations.organisation')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='LabelDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shipping_label', to='media_assets.mediaasset')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_labels', to='inventory.inventory')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_labels', to='organisations.organisation')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labels', to='shipping.shipment')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['organisation', 'status', '-created_at'], name='shipping_shipment_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.UniqueConstraint(fields=('organisation', 'number'), name='shipping_shipment_tenant_number_unique'),
        ),
        migrations.AddIndex(
            model_name='labeldocument',
            index=models.Index(fields=['organisation', 'shipment', '-created_at'], name='shipping_label_shipment_idx'),
        ),
    ]
