# Generated by Django 5.2.17 on 2026-08-26 15:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_backfill_stock_alerts'),
        ('media_assets', '0003_shipping_label'),
        ('organisations', '0002_initial'),
        ('shipping', '0001_shipment_state_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shipping_label', to='media_assets.mediaasset')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_labels', to='inventory.inventory')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_labels', to='organisations.organisation')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labels', to='shipping.shipment')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['organisation', 'shipment', '-created_at'], name='shipping_label_shipment_idx')],
            },
        ),
    ]
