# Generated by Django 5.2.17 on 2026-08-26 16:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_backfill_stock_alerts'),
        ('organisations', '0002_initial'),
        ('shipping', '0002_shipping_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('number', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('awaiting_seller', 'Espera al vendedor'), ('awaiting_buyer', 'Espera al comprador'), ('resolved', 'Resuelto'), ('closed', 'Cerrado')], default='open', max_length=24)),
                ('category', models.CharField(choices=[('not_received', 'No llegó'), ('damaged', 'Llegó dañado'), ('wrong_item', 'Producto equivocado'), ('other', 'Otra consulta')], default='other', max_length=24)),
                ('contact_name', models.CharField(blank=True, max_length=160)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_tickets', to='inventory.inventory')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_tickets', to='organisations.organisation')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='shipping.shipment')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('author_kind', models.CharField(choices=[('buyer', 'Comprador'), ('seller', 'Vendedor'), ('system', 'Sistema')], max_length=16)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='shipping.ticket')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['organisation', 'status', '-created_at'], name='shipping_ticket_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('organisation', 'number'), name='shipping_ticket_tenant_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('open', 'awaiting_seller', 'awaiting_buyer'))), fields=('shipment',), name='shipping_ticket_open_per_shipment'),
        ),
    ]
