# Generated by Django 5.2.17 on 2026-08-26 16:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_backfill_stock_alerts'),
        ('organisations', '0002_initial'),
        ('shipping', '0003_shipping_ticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='followupschedule',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='follow_ups', to='shipping.ticket'),
        ),
        migrations.CreateModel(
            name='ReturnCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('lost', 'Pérdida'), ('rejected', 'Rechazo'), ('returned', 'Devolución'), ('other', 'Otro')], max_length=24)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('stock_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_cases', to='inventory.inventory')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_cases', to='organisations.organisation')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_cases', to='shipping.shipment')),
                ('stock_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['organisation', 'shipment', '-created_at'], name='shipping_return_shipment_idx')],
            },
        ),
    ]
