# Generated by Django 5.2.17 on 2026-08-25 09:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider', models.CharField(max_length=40)),
                ('provider_event_id', models.CharField(max_length=160)),
                ('event_type', models.CharField(max_length=120)),
                ('raw_body', models.TextField()),
                ('safe_headers', models.JSONField(default=dict)),
                ('normalized_payload', models.JSONField(default=dict)),
                ('signature_valid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], default='received', max_length=16)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ('-received_at',),
                'indexes': [models.Index(fields=['status', 'received_at'], name='sales_webhook_processing_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_event_id'), name='sales_webhook_provider_event_unique')],
            },
        ),
    ]
