# Generated by Django 5.2.17 on 2026-08-25 09:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOAuthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider', models.CharField(choices=[('mercado_pago', 'Mercado Pago')], default='mercado_pago', max_length=40)),
                ('state_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organisations.organisation')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['provider', 'expires_at'], name='sales_oauth_state_expiry_idx')],
            },
        ),
        migrations.CreateModel(
            name='SellerPaymentConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider', models.CharField(choices=[('mercado_pago', 'Mercado Pago')], default='mercado_pago', max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='pending', max_length=16)),
                ('provider_account_id', models.CharField(blank=True, max_length=120)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('access_token_ciphertext', models.TextField(blank=True, editable=False)),
                ('refresh_token_ciphertext', models.TextField(blank=True, editable=False)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_payment_connections', to='organisations.organisation')),
            ],
            options={
                'ordering': ('provider',),
                'constraints': [models.UniqueConstraint(fields=('organisation', 'provider'), name='sales_seller_payment_connection_unique')],
            },
        ),
    ]
