# Generated by Django 5.2.17 on 2026-08-25 20:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_backfill_stock_alerts'),
        ('media_assets', '0002_alter_mediaasset_purpose'),
        ('organisations', '0002_initial'),
        ('sales', '0002_paymentoauthstate_sellerpaymentconnection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('number', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('reserved', 'Reservado'), ('purchase_in_progress', 'Proceso de compra'), ('purchase_validation', 'Validación de compra'), ('paid', 'Vendido'), ('cancelled', 'Cancelado'), ('expired', 'Expirado'), ('refunded', 'Reembolsado')], default='draft', max_length=24)),
                ('delivery_mode', models.CharField(choices=[('shipping', 'Despacho'), ('pickup', 'Retiro'), ('coordinated', 'A coordinar')], max_length=16)),
                ('payment_method', models.CharField(choices=[('mercado_pago', 'Mercado Pago'), ('bank_transfer', 'Transferencia'), ('cash', 'Efectivo')], max_length=24)),
                ('currency', models.CharField(default='CLP', editable=False, max_length=3)),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=14)),
                ('reservation_expires_at', models.DateTimeField()),
                ('expiry_paused_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('public_token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('public_token_ciphertext', models.TextField(editable=False)),
                ('public_token_expires_at', models.DateTimeField()),
                ('reconciliation_status', models.CharField(choices=[('ok', 'Sin diferencias'), ('required', 'Requiere conciliación'), ('retrying', 'Reintentando')], default='ok', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='inventory.inventory')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='organisations.organisation')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='paymentwebhookevent',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentwebhookevent',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentwebhookevent',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_webhook_events', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='paymentwebhookevent',
            name='provider_resource_id',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='paymentwebhookevent',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], default='received', max_length=16),
        ),
        migrations.CreateModel(
            name='BuyerSnapshot',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='buyer', serialize=False, to='sales.order')),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('recipient_name', models.CharField(blank=True, max_length=160)),
                ('address_line', models.CharField(blank=True, max_length=240)),
                ('municipality', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('delivery_notes', models.CharField(blank=True, max_length=500)),
                ('tax_id', models.CharField(blank=True, max_length=32)),
                ('tax_name', models.CharField(blank=True, max_length=180)),
                ('tax_activity', models.CharField(blank=True, max_length=180)),
                ('tax_address', models.CharField(blank=True, max_length=240)),
                ('tax_municipality', models.CharField(blank=True, max_length=120)),
                ('tax_city', models.CharField(blank=True, max_length=120)),
                ('tax_email', models.EmailField(blank=True, max_length=254)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='paymentwebhookevent',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='webhook_events', to='sales.order'),
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(max_length=80)),
                ('from_status', models.CharField(blank=True, max_length=24)),
                ('to_status', models.CharField(blank=True, max_length=24)),
                ('title', models.CharField(max_length=160)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timeline', to='sales.order')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('line_number', models.PositiveSmallIntegerField()),
                ('product_name', models.CharField(max_length=160)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_sale_price', models.DecimalField(decimal_places=0, max_digits=14)),
                ('unit_cost_snapshot', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True)),
                ('currency', models.CharField(default='CLP', editable=False, max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='sales.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='inventory.product')),
            ],
            options={
                'ordering': ('line_number', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('method', models.CharField(choices=[('mercado_pago', 'Mercado Pago'), ('bank_transfer', 'Transferencia'), ('cash', 'Efectivo')], max_length=24)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('validation', 'En validación'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado'), ('reconciliation_required', 'Requiere conciliación')], default='pending', max_length=32)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14)),
                ('currency', models.CharField(default='CLP', editable=False, max_length=3)),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('provider_account_id', models.CharField(blank=True, max_length=120)),
                ('provider_preference_id', models.CharField(blank=True, max_length=160)),
                ('checkout_url', models.URLField(blank=True, max_length=1000)),
                ('provider_payment_id', models.CharField(blank=True, max_length=160)),
                ('external_reference', models.CharField(blank=True, max_length=160)),
                ('provider_status', models.CharField(blank=True, max_length=80)),
                ('provider_status_detail', models.CharField(blank=True, max_length=160)),
                ('fee_requested', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('fee_reported', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True)),
                ('net_received', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True)),
                ('refunded_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('manual_note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='sales.order')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='organisations.organisation')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='paymentwebhookevent',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='webhook_events', to='sales.payment'),
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Carga pendiente'), ('ready', 'Por revisar'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=16)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment_proof', to='media_assets.mediaasset')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='proof', to='sales.payment')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReconciliationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('unknown_payment', 'Pago sin pedido'), ('payment_mismatch', 'Datos de pago distintos'), ('paid_without_stock', 'Pago sin salida de stock'), ('webhook_pending', 'Webhook pendiente'), ('fee_mismatch', 'Comisión distinta'), ('partial_refund', 'Reembolso parcial'), ('provider_status', 'Estado desconocido')], max_length=40)),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('retrying', 'Reintentando'), ('resolved', 'Resuelta')], default='open', max_length=16)),
                ('summary', models.CharField(max_length=240)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_issues', to='sales.order')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_issues', to='organisations.organisation')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_issues', to='sales.payment')),
                ('webhook_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_issues', to='sales.paymentwebhookevent')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('release_reason', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_reservations', to='inventory.inventory')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='sales.order')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reservation', to='sales.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_reservations', to='inventory.product')),
                ('stock_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumed_reservations', to='inventory.stockmovement')),
            ],
            options={
                'ordering': ('expires_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['organisation', 'status', '-created_at'], name='sales_order_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'reservation_expires_at'], name='sales_order_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['organisation', 'paid_at'], name='sales_order_paid_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('organisation', 'number'), name='sales_order_tenant_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='sales_order_total_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'CLP')), name='sales_order_currency_clp'),
        ),
        migrations.AddIndex(
            model_name='orderevent',
            index=models.Index(fields=['order', 'created_at'], name='sales_order_event_timeline_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product', 'order'], name='sales_order_item_product_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'line_number'), name='sales_order_item_line_unique'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sales_order_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_sale_price__gte', 0)), name='sales_order_item_sale_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost_snapshot__isnull', True), ('unit_cost_snapshot__gte', 0), _connector='OR'), name='sales_order_item_cost_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'CLP')), name='sales_order_item_currency_clp'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['organisation', 'status', 'paid_at'], name='sales_pay_tenant_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='sales_payment_amount_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('refunded_amount__gte', 0)), name='sales_payment_refund_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('refunded_amount__lte', models.F('amount'))), name='sales_payment_refund_within_amount'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'CLP')), name='sales_payment_currency_clp'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_payment_id', ''), _negated=True), fields=('provider', 'provider_payment_id'), name='sales_payment_provider_id_unique'),
        ),
        migrations.AddIndex(
            model_name='reconciliationissue',
            index=models.Index(fields=['organisation', 'status', '-created_at'], name='sales_reconcile_tenant_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationissue',
            index=models.Index(fields=['status', 'kind', '-created_at'], name='sales_reconcile_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['order', 'released_at', 'consumed_at'], name='sales_res_order_state_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['expires_at', 'released_at', 'consumed_at'], name='sales_reservation_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sales_reservation_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.CheckConstraint(condition=models.Q(('consumed_at__isnull', False), ('released_at__isnull', False), _negated=True), name='sales_reservation_single_terminal'),
        ),
    ]
